// dashboard/src/routes/v2/widget/[name].tsx
/**
 * /v2/widget/:name — single-widget xterm mirror.
 *
 * Solid port of `dashboard/app/v2/widget/[name]/page.tsx`. Calls
 * `fetchWidgetSpawn` to ask the daemon for the widget binary's cwd +
 * argv, then mounts a Terminal pinned to those values. The same PTY
 * WebSocket protocol drives both the in-app Terminal panes and this
 * standalone embed.
 *
 * Query parameters:
 *   - session   (required) — the session name the widget binds to.
 *   - dir       (required) — the working directory.
 *   - target    (optional) — passed through to the daemon as a hint.
 *   - theme     (optional) — JSON-encoded theme override.
 */

import { createSignal, onCleanup, onMount, Show, type JSX } from "solid-js";
import { A, useParams, useSearchParams } from "@solidjs/router";
import { Effect } from "effect";
import { Terminal } from "@/components/Terminal";
import { fetchWidgetSpawn, type WidgetSpawnSpec } from "@/lib/api";

type LoadState =
  | { kind: "loading" }
  | { kind: "ready"; spec: WidgetSpawnSpec; id: string }
  | { kind: "error"; message: string };

export default function WidgetRoute(): JSX.Element {
  const params = useParams<{ name: string }>();
  const [search] = useSearchParams<{
    session?: string;
    dir?: string;
    target?: string;
    theme?: string;
  }>();

  const [state, setState] = createSignal<LoadState>({ kind: "loading" });

  const widgetName = () => params.name ?? "";
  const session = () => (typeof search.session === "string" ? search.session : "");
  const dir = () => (typeof search.dir === "string" ? search.dir : "");
  const target = () => (typeof search.target === "string" ? search.target : undefined);
  const themeRaw = () => (typeof search.theme === "string" ? search.theme : undefined);
  const bridgeId = () => `widget:${widgetName()}:${session()}:${target() ?? "*"}`;

  onMount(() => {
    let cancelled = false;
    if (!widgetName() || !session() || !dir()) {
      setState({
        kind: "error",
        message: "missing widget name, session, or dir query params",
      });
      return;
    }
    void (async () => {
      try {
        let theme: unknown = undefined;
        const raw = themeRaw();
        if (raw) {
          try {
            theme = JSON.parse(raw);
          } catch {
            throw new Error("theme query param must be valid JSON");
          }
        }
        const fetchParams: {
          session: string;
          dir: string;
          target?: string;
          theme?: unknown;
        } = { session: session(), dir: dir() };
        const t = target();
        if (t) fetchParams.target = t;
        if (theme !== undefined) fetchParams.theme = theme;
        const spec = await Effect.runPromise(fetchWidgetSpawn(widgetName(), fetchParams));
        if (cancelled) return;
        setState({ kind: "ready", spec, id: bridgeId() });
      } catch (err) {
        if (cancelled) return;
        setState({
          kind: "error",
          message: err instanceof Error ? err.message : String(err),
        });
      }
    })();
    onCleanup(() => {
      cancelled = true;
    });
  });

  return (
    <div
      data-testid="v2-widget-route"
      data-widget-name={widgetName()}
      class="flex h-screen flex-col bg-[var(--bg)] text-[var(--fg)]"
    >
      <header class="flex h-7 shrink-0 items-center border-b border-[var(--border)] bg-[var(--bg-strong)] px-3 text-sm tabular-nums">
        <A
          href="/v2"
          class="mr-2 inline-flex items-center gap-1 text-[var(--dim)] hover:text-[var(--fg)]"
        >
          <span aria-hidden="true">◇</span>
          <span>tmux-ide</span>
        </A>
        <span class="mx-1 text-[var(--dimmer)]">/</span>
        <span>widget</span>
        <span class="mx-1 text-[var(--dimmer)]">/</span>
        <span class="font-medium text-[var(--accent)]">{widgetName()}</span>
        <Show when={session()}>
          <span class="mx-1 text-[var(--dimmer)]">·</span>
          <span class="text-[var(--fg-secondary)]">{session()}</span>
        </Show>
        <Show when={target()}>
          <span class="mx-1 text-[var(--dimmer)]">·</span>
          <span class="truncate text-[var(--dim)]">{target()}</span>
        </Show>
        <span class="flex-1" />
        <span class="text-[var(--dim)]">PTY mirror</span>
      </header>

      <div class="flex-1 min-h-0">
        <Show when={state().kind === "loading"}>
          <div
            data-testid="v2-widget-loading"
            class="flex h-full items-center justify-center text-[var(--dim)]"
          >
            resolving widget…
          </div>
        </Show>
        <Show when={state().kind === "error"}>
          {(_) => {
            const s = state();
            if (s.kind !== "error") return null;
            return (
              <div
                data-testid="v2-widget-error"
                class="flex h-full items-center justify-center px-6 text-center text-[var(--red-foreground,var(--red))]"
              >
                <div>
                  <div class="mb-2 text-base uppercase tracking-wider">widget unavailable</div>
                  <div class="text-sm text-[var(--dim)]">{s.message}</div>
                </div>
              </div>
            );
          }}
        </Show>
        <Show when={state().kind === "ready"}>
          {(_) => {
            const s = state();
            if (s.kind !== "ready") return null;
            return <Terminal id={s.id} showHeader={false} cwd={s.spec.cwd} cmd={s.spec.cmd} />;
          }}
        </Show>
      </div>
    </div>
  );
}

// dashboard/app/v2/widget/[name]/page.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useParams, useSearchParams } from "next/navigation";
import { Terminal } from "@/components/Terminal";
import { fetchWidgetSpawn, type WidgetSpawnSpec } from "@/lib/api";

type LoadState =
  | { kind: "loading" }
  | { kind: "ready"; spec: WidgetSpawnSpec; id: string }
  | { kind: "error"; message: string };

export default function WidgetMirrorPage() {
  const params = useParams<{ name: string }>();
  const search = useSearchParams();
  const widgetName = params?.name ?? "";

  const session = search?.get("session") ?? "";
  const dir = search?.get("dir") ?? "";
  const target = search?.get("target");
  const themeRaw = search?.get("theme");

  const bridgeId = useMemo(() => {
    const t = target ?? "*";
    return `widget:${widgetName}:${session}:${t}`;
  }, [widgetName, session, target]);

  const [state, setState] = useState<LoadState>({ kind: "loading" });

  useEffect(() => {
    if (!widgetName || !session || !dir) {
      setState({ kind: "error", message: "missing widget name, session, or dir query params" });
      return;
    }
    let cancelled = false;
    (async () => {
      try {
        let theme: unknown = undefined;
        if (themeRaw) {
          try {
            theme = JSON.parse(themeRaw);
          } catch {
            throw new Error("theme query param must be valid JSON");
          }
        }
        const fetchParams: { session: string; dir: string; target?: string; theme?: unknown } = {
          session,
          dir,
        };
        if (target) fetchParams.target = target;
        if (theme !== undefined) fetchParams.theme = theme;
        const spec = await fetchWidgetSpawn(widgetName, fetchParams);
        if (cancelled) return;
        setState({ kind: "ready", spec, id: bridgeId });
      } catch (err) {
        if (cancelled) return;
        setState({
          kind: "error",
          message: err instanceof Error ? err.message : String(err),
        });
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [widgetName, session, dir, target, themeRaw, bridgeId]);

  return (
    <div className="flex h-screen flex-col bg-[var(--bg)] text-[var(--fg)]">
      <header className="flex h-7 shrink-0 items-center border-b border-[var(--border)] bg-[var(--bg-strong)] px-3 text-[11px] tabular-nums">
        <Link href="/v2" className="mr-2 inline-flex items-center gap-1 text-[var(--dim)] hover:text-[var(--fg)]">
          <span aria-hidden="true">◇</span>
          <span>tmux-ide</span>
        </Link>
        <span className="mx-1 text-[var(--dimmer)]">/</span>
        <span>widget</span>
        <span className="mx-1 text-[var(--dimmer)]">/</span>
        <span className="font-medium text-[var(--accent)]">{widgetName}</span>
        {session && (
          <>
            <span className="mx-1 text-[var(--dimmer)]">·</span>
            <span className="text-[var(--fg-secondary)]">{session}</span>
          </>
        )}
        {target && (
          <>
            <span className="mx-1 text-[var(--dimmer)]">·</span>
            <span className="truncate text-[var(--dim)]">{target}</span>
          </>
        )}
        <span className="flex-1" />
        <span className="text-[var(--dim)]">PTY mirror</span>
      </header>

      <div className="flex-1 min-h-0">
        {state.kind === "loading" && (
          <div className="flex h-full items-center justify-center text-[var(--dim)]">
            resolving widget…
          </div>
        )}
        {state.kind === "error" && (
          <div className="flex h-full items-center justify-center px-6 text-center text-[var(--red)]">
            <div>
              <div className="mb-2 text-[12px] uppercase tracking-wider">widget unavailable</div>
              <div className="text-[11px] text-[var(--dim)]">{state.message}</div>
            </div>
          </div>
        )}
        {state.kind === "ready" && (
          <Terminal
            id={state.id}
            className="h-full w-full"
            showHeader={false}
            cwd={state.spec.cwd}
            cmd={state.spec.cmd}
          />
        )}
      </div>
    </div>
  );
}
